services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: finance_manager
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PASSWORD=123456
      - APP_DEBUG=false

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80" #  唯一对外的安全大门

volumes:
  mysql_data:
    external: true
    name: finance_manager_mysql_data